# Generated by Django 5.0.3 on 2024-05-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Forja', '0002_remove_chatroom_name_alter_chatmessage_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
