# Generated by Django 5.0.3 on 2024-05-11 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Forja', '0003_remove_chatmessage_room_remove_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('jogador', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('nivel', models.IntegerField()),
                ('tendencia', models.CharField(blank=True, max_length=100)),
                ('antecedente', models.CharField(blank=True, max_length=100)),
                ('forca', models.IntegerField()),
                ('destreza', models.IntegerField()),
                ('constituicao', models.IntegerField()),
                ('inteligencia', models.IntegerField()),
                ('sabedoria', models.IntegerField()),
                ('carisma', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('ca', models.IntegerField()),
                ('pericias', models.TextField(blank=True)),
                ('historia', models.TextField(blank=True)),
                ('equipamentos', models.TextField(blank=True)),
                ('magias', models.TextField(blank=True)),
                ('habilidades_classe', models.TextField(blank=True)),
                ('tracos_raciais', models.TextField(blank=True)),
                ('proficiencia', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
