# Generated by Django 5.0.3 on 2024-05-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Forja', '0004_ficha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='usuario',
        ),
    ]
