# Generated by Django 5.0.3 on 2024-05-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Forja', '0006_ficha_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
