# Generated by Django 5.0.3 on 2024-05-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Forja', '0007_alter_ficha_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('nivel', models.IntegerField()),
                ('antecedente', models.CharField(blank=True, max_length=100)),
                ('jogador', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('alinhamento', models.CharField(blank=True, max_length=100)),
                ('experiencia', models.IntegerField(default=0)),
                ('forca', models.IntegerField()),
                ('destreza', models.IntegerField()),
                ('constituicao', models.IntegerField()),
                ('inteligencia', models.IntegerField()),
                ('sabedoria', models.IntegerField()),
                ('carisma', models.IntegerField()),
                ('inspiracao', models.IntegerField()),
                ('bonus_prof', models.IntegerField()),
                ('salvaguardas', models.TextField(blank=True)),
                ('pericias', models.TextField(blank=True)),
                ('sabedoria_passiva', models.IntegerField(default=10)),
                ('outras', models.TextField(blank=True)),
                ('ca', models.IntegerField()),
                ('iniciativa', models.IntegerField(default=0)),
                ('deslocamento', models.IntegerField(default=30)),
                ('hp_max', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('hp_temp', models.IntegerField(default=0)),
                ('dado_vida', models.CharField(blank=True, max_length=20)),
                ('sg_morte', models.JSONField(default=list)),
                ('ataques_magias', models.TextField(blank=True)),
                ('historia', models.TextField(blank=True)),
                ('equipamento', models.TextField(blank=True)),
                ('habilidades_classe', models.TextField(blank=True)),
                ('tracos_personalidade', models.TextField(blank=True)),
                ('ideais', models.TextField(blank=True)),
                ('vinculos', models.TextField(blank=True)),
                ('fraquezas', models.TextField(blank=True)),
                ('caracteristicas_talentos', models.TextField(blank=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('altura', models.CharField(blank=True, max_length=20)),
                ('peso', models.CharField(blank=True, max_length=20)),
                ('olhos', models.CharField(blank=True, max_length=20)),
                ('pele', models.CharField(blank=True, max_length=20)),
                ('cabelo', models.CharField(blank=True, max_length=20)),
                ('ali_org', models.TextField(blank=True)),
                ('caracteristicas_adc', models.TextField(blank=True)),
                ('tesouro', models.TextField(blank=True)),
                ('classe_conjuradora', models.CharField(max_length=100)),
                ('atrib_conjura', models.CharField(max_length=100)),
                ('cd_miss', models.CharField(max_length=100)),
                ('modificador_am', models.CharField(max_length=100)),
                ('truques', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
