# Generated by Django 5.0.3 on 2024-05-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Forja', '0009_rename_equipamentos_ficha_ali_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='salvaguardas',
            field=models.TextField(blank=True, default=list, null=True),
        ),
    ]
