# Generated by Django 5.0.3 on 2024-05-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Forja', '0010_alter_ficha_salvaguardas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='salvaguardas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='sg_morte',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
