# Generated by Django 5.0.3 on 2024-05-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Forja', '0013_remove_ficha_habilidades_classe_alter_ficha_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='sg_morte',
        ),
        migrations.AddField(
            model_name='ficha',
            name='falhas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='sucessos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
