# Generated by Django 5.0.3 on 2024-05-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Forja', '0014_remove_ficha_sg_morte_ficha_falhas_ficha_sucessos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='altura',
            field=models.PositiveIntegerField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='falhas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idade',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='peso',
            field=models.PositiveIntegerField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='sucessos',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
