# Generated by Django 5.0.3 on 2024-05-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Forja', '0016_alter_ficha_altura_alter_ficha_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='falhas',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
