# Generated by Django 5.0.3 on 2024-05-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Forja', '0018_remove_ficha_id_ficha_id_ficha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='id_ficha',
            new_name='id',
        ),
    ]
