# Generated by Django 5.0.3 on 2024-05-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Forja', '0019_rename_id_ficha_ficha_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
