# Generated by Django 5.0.3 on 2024-07-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Forja', '0021_alter_ficha_idade'),
    ]

    operations = [
    ]
